workflows:
  teamflo-ios:
    name: TeamFloApp iOS Build
    scripts:
      - name: Build Flutter App
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/**/*.ipa