// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNHvZkMJenLDv4VaZcw0lxRE0AkL6kV5g',
    appId: '1:221166539130:web:8c60ae25438ee0acd046c3',
    messagingSenderId: '221166539130',
    projectId: 'teamfloapp',
    authDomain: 'teamfloapp.firebaseapp.com',
    storageBucket: 'teamfloapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXzRQcS03n_ntuWB7-sy8Mgh1ibWW9yk8',
    appId: '1:221166539130:android:f00d26ba0c041a37d046c3',
    messagingSenderId: '221166539130',
    projectId: 'teamfloapp',
    storageBucket: 'teamfloapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNEijZGJALHVRzoEF9T0uS09dWoZcwaak',
    appId: '1:221166539130:ios:5a9ecc9b60e9ceb2d046c3',
    messagingSenderId: '221166539130',
    projectId: 'teamfloapp',
    storageBucket: 'teamfloapp.firebasestorage.app',
    iosBundleId: 'com.example.teamFloApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNEijZGJALHVRzoEF9T0uS09dWoZcwaak',
    appId: '1:221166539130:ios:5a9ecc9b60e9ceb2d046c3',
    messagingSenderId: '221166539130',
    projectId: 'teamfloapp',
    storageBucket: 'teamfloapp.firebasestorage.app',
    iosBundleId: 'com.example.teamFloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNHvZkMJenLDv4VaZcw0lxRE0AkL6kV5g',
    appId: '1:221166539130:web:6367a5ef8e42230ed046c3',
    messagingSenderId: '221166539130',
    projectId: 'teamfloapp',
    authDomain: 'teamfloapp.firebaseapp.com',
    storageBucket: 'teamfloapp.firebasestorage.app',
  );
}
